"""The prose that tells the main session to keep a stage's pending questions
on disk (via pending.py) and to resume from them. A script that nobody is
told to call saves nothing, so these hold the instructions in place.

Both trees carry the wording -- `plugins/cai` by hand, `plugins/cai-codex`
regenerated by `scripts/gen-codex.py`, which rewrites the interpreter call
`python <plugin root>/scripts/pending.py` into `<cai> pending` -- so each
check runs against both.
"""
import os
import re

import pytest

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TREES = ["plugins/cai", "plugins/cai-codex"]


def _flat(plugin_root, *parts):
    with open(os.path.join(ROOT, plugin_root, "skills", "track", *parts),
              encoding="utf-8") as fh:
        return " ".join(fh.read().split())


def _command(text, verb):
    """Either tree's spelling of `pending.py <verb>`."""
    return re.search(r"(?:pending\.py|<cai> pending) %s " % verb, text)


def _section(text, start, end):
    return text[text.index(start):text.index(end)]


@pytest.mark.parametrize("plugin_root", TREES)
def test_the_round_is_saved_before_the_first_question(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    saved = _section(text, "**Save the round before asking anything.**",
                     "0. **Lay the options out")
    assert _command(saved, "start")
    assert "--report-file" in saved
    assert "verbatim" in saved
    assert "only thing that writes that file" in saved
    assert "wrote nothing" in saved and "outlive the session" in saved


@pytest.mark.parametrize("plugin_root", TREES)
def test_each_answer_is_saved_and_a_timed_out_menu_is_not(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    step1 = _section(text, "1. **Ask one decision per turn.**", "2. **Re-dispatch")
    assert "Save each answer before asking the next question" in step1
    assert _command(step1, "answer") and "--answer-file" in step1
    assert "closes on its own gets no such call" in step1
    assert "stays `open`" in step1


@pytest.mark.parametrize("plugin_root", TREES)
def test_redispatch_quotes_the_saved_report_when_resumed(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    step2 = _section(text, "2. **Re-dispatch", "3. **Three rounds at most.**")
    assert "`pending.md`" in step2 and "resumed session quotes them from there" in step2


@pytest.mark.parametrize("plugin_root", TREES)
def test_resuming_asks_the_first_open_question_and_ignores_unusable_files(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    resume = _section(text, "## Resuming a saved round", "## Clearing it")
    assert "`pending:` section" in resume
    assert "Do not run the stage's preflight and dispatch again" in resume
    assert "first question marked `open`" in resume
    assert "go straight to step 2" in resume
    assert "already `done` or `skipped`" in resume and "ask nothing from it" in resume


@pytest.mark.parametrize("plugin_root", TREES)
def test_clear_follows_a_result_and_blocked_or_unavailable_keep_the_file(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    clear = _section(text, "## Clearing it", "## What this is not")
    assert "exits 0" in clear and _command(clear, "clear")
    assert "`passed`, `failed` or `skipped`" in clear
    assert "`blocked` or `unavailable`" in clear and "the file stays" in clear


def test_manual_lists_pending_md_and_no_longer_says_the_round_dies():
    with open(os.path.join(ROOT, "MANUAL.md"), encoding="utf-8") as fh:
        text = fh.read()
    flat = " ".join(text.split())
    assert "    pending.md  " in text
    assert "dies with the conversation" not in flat
    assert "saves it to `pending.md` before asking" in flat
    # A gate a stage hands up under `## Pending questions` is saved like any
    # other question; only a menu with no stage report behind it is not.
    assert "is saved, a human gate handed up that way included" in flat
    assert ("A menu the main session raises itself, with no stage report "
            "behind it, is not saved") in flat
    assert "the two human gates and the other stops" not in flat


@pytest.mark.parametrize("plugin_root", TREES)
def test_an_unreadable_pending_md_is_named_and_the_round_goes_unsaved(plugin_root):
    text = _flat(plugin_root, "references", "pending-questions.md")
    saved = _section(text, "**Save the round before asking anything.**",
                     "0. **Lay the options out")
    assert "a `pending.md` it cannot read or does not recognise" in saved
    assert "ask the person to delete `<track-dir>/pending.md`" in saved
    assert "without saving this round" in saved


@pytest.mark.parametrize("plugin_root", TREES)
def test_skill_md_resume_path_routes_a_pending_section_to_the_reference(plugin_root):
    text = _flat(plugin_root, "SKILL.md")
    at = text.index("A `pending:` section in `track_state.py status`")
    sentence = text[at:text.index("## Human gates")]
    assert "`references/pending-questions.md`" in sentence
    assert "first `open` question" in sentence
    assert "instead of running the stage again" in sentence
    assert _command(sentence, "clear")


@pytest.mark.parametrize("plugin_root", ["plugins/cai", "plugins/cai-codex"])
def test_report_and_answers_go_in_on_stdin_with_a_powershell_fallback(plugin_root):
    # #345: one scratch file per report, answer and draft meant one deletion
    # each, and Codex stopped to approve every one. Piped in, there is none.
    path = os.path.join(os.path.dirname(__file__), "..", plugin_root,
                        "skills", "track", "references", "pending-questions.md")
    with open(path, encoding="utf-8") as fh:
        flat = " ".join(fh.read().split())
    assert "--report-file -`" in flat and "--answer-file -`" in flat
    assert "<<'CAI_PENDING_EOF'" in flat
    assert flat.count("PowerShell") >= 3
