"""Issue #316: inside a track, `ship` starts as soon as `verify` passes.

Typing `ship` after `verify` was a step taken almost every time, and what it
started -- the shipper's draft -- changes nothing, so the person waited for a
draft they could have had already. Gate 2 still stands between the draft and
anything irreversible.

Text pins, not behaviour: the procedure is prose the main session follows.
`SKILL.md` routes and carries one pointer line; the rule itself lives in
`approval-gates.md`'s Gate 2. They read `plugins/cai` (the source) and
`plugins/cai-codex` (generated by scripts/gen-codex.py), since Codex runs the
same track.
"""
import json
import os
import re

import pytest

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TRACK = os.path.join("skills", "track")
PLUGINS = ["plugins/cai", "plugins/cai-codex"]


def _read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return fh.read()


def _flat(text):
    return " ".join(text.split())


def _human_gates(plugin_root):
    text = _read(plugin_root, TRACK, "SKILL.md")
    start = text.index("\n## Human gates\n")
    return _flat(text[start + 1:text.index("\n## ", start + 1)])


def _gate2(plugin_root):
    text = _read(plugin_root, TRACK, "references", "approval-gates.md")
    start = text.index("\n## Gate 2")
    return _flat(text[start + 1:text.index("\n## ", start + 1)])


@pytest.mark.parametrize("plugin_root", PLUGINS)
def test_skill_md_points_at_gate_2_for_ship_starting_unasked(plugin_root):
    gates = _human_gates(plugin_root)
    assert "Yet `ship` starts unasked once `verify` passes: " \
           "`approval-gates.md`'s Gate 2 says why and how (#316)." in gates
    # The two-gate rule is untouched: this starts a draft, it adds no stop.
    assert "it is not a third human gate" in gates


@pytest.mark.parametrize("plugin_root", PLUGINS)
def test_gate2_starts_ship_once_verify_passes_and_runs_nothing_irreversible(plugin_root):
    gate = _gate2(plugin_root)
    assert "Inside a track, nobody types `ship` (#316)." in gate
    assert "start `ship` without waiting to be asked: preflight, the draft " \
           "dispatch, then this menu" in gate
    # After verify's own commit, or the draft describes a HEAD about to move.
    assert "\"Verify's changes, inside a track\" below has run" in gate
    assert "Nothing irreversible runs before the menu's \"Run them\"" in gate


@pytest.mark.parametrize("plugin_root", PLUGINS)
def test_an_unasked_preflight_failure_spends_no_retry(plugin_root):
    gate = _gate2(plugin_root)
    assert "If that preflight exits 2, report every line it printed and " \
           "append nothing to the ledger" in gate
    assert "a `blocked` row would spend one of its retries" in gate
    assert "`ship` then waits to be asked" in gate
    # A fix round already chains verify into ship and keeps its own rules.
    assert "by its own rules under `### A fix round`" in gate


def test_ship_keeps_auto_invoke_false_so_cai_ship_alone_still_waits():
    # Guard, passes before the fix too: the change must not be made by
    # flipping the flag, which would also let `/cai:ship` start on a matching
    # sentence (scripts/validate.py ties the flag to disable-model-invocation).
    stages = json.loads(_read("plugins/cai", TRACK, "stages.json"))["stages"]
    ship = [row for row in stages if row["id"] == "ship"][0]
    assert ship["auto_invoke"] is False
    assert "disable-model-invocation: true" in _read("plugins/cai", "skills", "ship", "SKILL.md")


@pytest.mark.parametrize("plugin_root", PLUGINS)
def test_gate2_says_what_free_text_does_on_a_menu_nobody_asked_for(plugin_root):
    gate = _gate2(plugin_root)
    assert "Inside a track this menu can arrive unasked" in gate
    assert "run `ship_draft_check.py` on the changed draft again, and put the " \
           "menu again with the new text in full" in gate
    assert "**Not yet** → nothing runs and nothing is recorded" in gate
    # Clearing the saved round is what keeps a later resume from re-asking
    # with drafts of an older commit. Codex spells the call `<cai> pending`.
    assert re.search(r"pending(\.py)? clear --track-dir "
                     r"\.claude/track/<feature> --stage ship", gate)
    assert "drafts again from the branch as it then stands" in gate


def test_manual_says_ship_arrives_as_its_menu():
    manual = _flat(_read("MANUAL.md"))
    assert "starts on its own once `verify` passes, so you never type `ship`" in manual
