#!/usr/bin/env python3
"""
Generate one slash command per refactoring from the catalog index.

Every generated command carries `disable-model-invocation: true`: the 72
descriptions total far more than the always-on budget allows, so they must
stay out of the model's context while remaining user-invocable for tab
completion. Run this when you want the individual commands:

    python3 gen-commands.py              # write refactoring-catalog/<slug>/SKILL.md
    python3 gen-commands.py --list       # print the catalog, write nothing
    python3 gen-commands.py --only extract-method move-method
    python3 gen-commands.py --clean      # remove generated commands

Single source of truth: skills/refactor/references/catalog-index.md
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "skills" / "refactor" / "references" / "catalog-index.md"
COMMANDS = ROOT / "refactoring-catalog"

CHAPTER_FILES = {
    "Composing Methods": "cat-06-composing-methods.md",
    "Moving Features Between Objects": "cat-07-moving-features.md",
    "Organizing Data": "cat-08-organizing-data.md",
    "Simplifying Conditional Expressions": "cat-09-conditionals.md",
    "Making Method Calls Simpler": "cat-10-method-calls.md",
    "Dealing with Generalization": "cat-11-generalization.md",
    "Big Refactorings": "cat-12-big-refactorings.md",
}

RISK_LABEL = {
    "L": "local and mechanical",
    "M": "crosses class boundaries",
    "H": "wide blast radius — read the preconditions carefully",
}

ROW = re.compile(
    r"^\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*`([a-z0-9-]+)`\s*\|\s*([LMH])\s*\|\s*(.+?)\s*\|\s*$"
)
HEADING = re.compile(r"^##\s+(.+?)\s+→\s+`(cat-\d+[a-z0-9-]*\.md)`\s*$")

GENERATED_MARKER = "<!-- generated by gen-commands.py -->"

TEMPLATE = """---
name: {slug}
description: >-
  Apply the {name} refactoring ({risk_label}). Fixes {fixes}.
  Executes the catalog mechanics one step at a time, testing after each step.
argument-hint: "<target — file:line-range, class, or method>"
allowed-tools: Read, Write, Edit, Grep, Glob, Bash
disable-model-invocation: true
---

{marker}

# {name}

Catalog #{num} · {chapter} · risk **{risk}** ({risk_label})
Addresses: {fixes}

Target: `$ARGUMENTS`

## Do this

1. Read the **{name}** card in
   `${{CLAUDE_PLUGIN_ROOT}}/skills/refactor/references/{chapter_file}`.
   Its **Pre** and **Mechanics** sections are authoritative — this command does
   not restate them, so that there is one source of truth.
2. Apply the safety protocol yourself: pre-flight, step-by-step mechanics with
   a test after each step, full suite, commit. It is defined once in
   `${{CLAUDE_PLUGIN_ROOT}}/skills/refactor/SKILL.md` under
   "## Non-negotiable safety protocol"; it is not restated here. The heading
   is the anchor on purpose -- a line number here would be stale the next time
   anything above it is edited, in all 72 of these files at once.
3. Behaviour must not change. Do not modify tests except for a rename you name
   explicitly in the report. Do not start a second refactoring — report any
   follow-up the card indicates instead.

If a precondition fails, stop and name the correct alternative refactoring rather
than forcing this one.
"""


def parse_index(path: Path):
    entries, chapter, chapter_file = [], None, None
    for line in path.read_text(encoding="utf-8").splitlines():
        h = HEADING.match(line)
        if h:
            chapter, chapter_file = h.group(1), h.group(2)
            continue
        m = ROW.match(line)
        if m and chapter:
            num, name, slug, risk, fixes = m.groups()
            entries.append({
                "num": int(num),
                "name": name,
                "slug": slug,
                "risk": risk,
                "risk_label": RISK_LABEL[risk],
                "fixes": fixes,
                "chapter": chapter,
                "chapter_file": chapter_file or CHAPTER_FILES.get(chapter, ""),
            })
    return entries


def write_commands(entries, only=None):
    COMMANDS.mkdir(exist_ok=True)
    written = 0
    for e in entries:
        if only and e["slug"] not in only:
            continue
        target_dir = COMMANDS / e["slug"]
        target = target_dir / "SKILL.md"
        if target.exists() and GENERATED_MARKER not in target.read_text(encoding="utf-8"):
            print(f"  skip (hand-edited): {target}", file=sys.stderr)
            continue
        target_dir.mkdir(exist_ok=True)
        target.write_text(TEMPLATE.format(marker=GENERATED_MARKER, **e), encoding="utf-8")
        written += 1
    return written


def clean():
    if not COMMANDS.exists():
        return 0
    removed = 0
    for f in COMMANDS.glob("*/SKILL.md"):
        if GENERATED_MARKER in f.read_text(encoding="utf-8"):
            f.unlink()
            f.parent.rmdir()
            removed += 1
    return removed


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="print the catalog as JSON, write nothing")
    ap.add_argument("--only", nargs="+", metavar="SLUG", help="generate only these slugs")
    ap.add_argument("--clean", action="store_true", help="remove generated command files")
    args = ap.parse_args()

    if args.clean:
        print(f"Removed {clean()} generated command(s).")
        return

    if not INDEX.exists():
        sys.exit(f"catalog index not found: {INDEX}")

    entries = parse_index(INDEX)
    if len(entries) != 72:
        print(f"warning: parsed {len(entries)} entries, expected 72", file=sys.stderr)

    if args.list:
        json.dump(entries, sys.stdout, indent=2, ensure_ascii=False)
        print()
        return

    n = write_commands(entries, set(args.only) if args.only else None)
    print(f"Wrote {n} command(s) to {COMMANDS}/")
    print("Restart Claude Code or run /reload-plugins to pick them up.")


if __name__ == "__main__":
    main()
